spring.application.name=gestion-notes
server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5433/gestion_notes
spring.datasource.username=notes_user
spring.datasource.password=notes1234

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true